### ISSUE TITLE
[BUG]Is it different from traditional spectral clustering?

### ISSUE THREAD

**Issue by EmilyLike** [tczhangzhi/cluster#1]
Traditional spectral clustering selects k eigenvectors with smaller eigenvalues for K-Means clustering. But this project use svd matrix decomposition?
```
...
u, s, v = torch.svd(sym_laplican)
return self.cluster(u[:, -self.k:])
...
```

**Comment by tczhangzhi** [comment]
You are right. WIP.

**Comment by tczhangzhi** [comment]
Fixed.
